/* 
This project is an emergence art, creating wave lines with foam-like effects using p5.js.
The wavy lines are generated by using Perlin Noise, and it is constantly evolving and changing. 
*/

let yOffset = 0.0; // This is Y offset for wave movement
let waveColor; // Color of the lines
let numWaveLines; // number of the lines
let lastChangeTime = 0; // Time of the last change
const changeInterval = 3000; // Change every 3 seconds

function setup() {
  const canvasContainer = document.getElementById('canvas-container');
  const canvas = createCanvas(800, 800);
  waveColor = color(0, 100, 200, 50); // Light blue with transparency
  noFill();
  
  numWaveLines = Math.floor(random(1, 8)); // Randomly select the initial number of wave lines
  lastChangeTime = millis(); // Set the initial time of the last change
}

function draw() {
  background(0, 30); // Fade the background slightly each frame

  const smallerSize = min(width, height);
  const constraints = [smallerSize * 0.05, smallerSize * 0.95];

  // Draw wave-like lines
  stroke(waveColor);
  strokeWeight(2);

  // For loop for drawing multiple lines  
  for (let i = 0; i < numWaveLines; i++) {
    beginShape();
    const yOff = yOffset + i * 0.1; // Y offset for each line
    let xOffset = 0.00; // X offset for noise function
    const step = 20;

    for (let x = constraints[0]; x < constraints[1] + step / 2; x += step) {
      const y = map(noise(xOffset, yOff), 0, 1, constraints[0], constraints[1]); // Map noise value to Y position
      vertex(x, y); // Add vertex to the shape
      xOffset += 0.05; // X offset increment for the noise function
    }

    endShape();
  }

  // Draw foam-like dots
  stroke(255); // White color fo the dots
  strokeWeight(2);
  const foamCount = 1; // Number of dot to draw
  for (let i = 0; i < foamCount; i++) {
    const x = random(constraints[0], constraints[1]); // Random X position for dots
    const y = random(constraints[0], constraints[1]); // Random Y position for dots
    const foamSize = random(2, 6); // Random size for the dots
    point(x, y, foamSize);
  }

  yOffset += 0.005; // Y offset value increment for wave

  // If function to check the time to change the number of lines
  if (millis() - lastChangeTime >= changeInterval) {
    numWaveLines = Math.floor(random(1, 11)); // Randomly change the number of wave lines
    lastChangeTime = millis(); // Update the time of the last change
  }
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight); // Resize the canvas responsively
}
